test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails secrets:edit to set the AWS secrets (as shared:aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: ****************
  secret_access_key: *********************************************
  region: us-west-2
  bucket: gstroop-production</pre>

google:
  service: GCS
  project: ******-******
  keyfile: <%= Rails.root.join("config/gcs.json") %>
  bucket: ****-*******-**** </pre>

mirror:
  service: Mirror
  primary: local
  mirrors: [ amazon, google ]
